name: Build Image Action
description: Shared steps to checkout, setup qemu, and build container image
inputs:
  image_tags:
    description: Tags for the built image
    required: true
outputs:
  image:
    description: Name of the built image
    value: ${{ steps.build_image.outputs.image }}
  tags:
    description: Tags of the built image
    value: ${{ steps.build_image.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install qemu dependency
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static

    - name: Build Image
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ github.event.repository.name }}
        tags: ${{ inputs.image_tags }}
        archs: amd64, arm64, ppc64le, riscv64, s390x
        containerfiles: |
          ./Dockerfile
